Repository giovannivolpe/BRAPH-2-Matlab-beta, pull requests merged in 2023-09, with the labels that each got.

#129 NN Cross Validation
  braph2genesis/neuralnetworks/_NNClassifier_CrossValidation.gen.m
  braph2genesis/neuralnetworks/_NNClassifier_Evaluator.gen.m
  braph2genesis/neuralnetworks/_NNRegressor_CrossValidation.gen.m
  braph2genesis/neuralnetworks/_NNRegressor_Evaluator.gen.m
  braph2genesis/pipelines/connectivity NN/_NNDataPoint_CON_CLA.gen.m
  braph2genesis/pipelines/connectivity NN/_NNDataPoint_CON_REG.gen.m
  braph2genesis/pipelines/connectivity NN/example_NNCV_CON_CLA.m
  braph2genesis/pipelines/connectivity NN/example_NNCV_CON_REG.m
  braph2genesis/pipelines/connectivity NN/example_NN_CON_CLA.m
  braph2genesis/pipelines/connectivity NN/example_NN_CON_REG.m
  braph2genesis/pipelines/connectivity NN/pipeline_connectivity_classification_cross_validation.braph2
  braph2genesis/pipelines/connectivity NN/pipeline_connectivity_regression_cross_validation.braph2
  braph2genesis/src/nn/_NNCrossValidation.gen.m
  braph2genesis/src/nn/_NNDatasetSplit.gen.m
Labels: enhancement

#152 NN feature importance
  braph2genesis/measures/_GlobalEfficiencyAv.gen.m
  braph2genesis/neuralnetworks/_NNClassifierMLP.gen.m
  braph2genesis/neuralnetworks/_NNClassifier_CrossValidation.gen.m
  braph2genesis/neuralnetworks/_NNClassifier_Evaluator.gen.m
  braph2genesis/neuralnetworks/_NNRegressorMLP.gen.m
  braph2genesis/neuralnetworks/_NNRegressor_CrossValidation.gen.m
  braph2genesis/neuralnetworks/_NNRegressor_Evaluator.gen.m
  braph2genesis/pipelines/connectivity NN/example_NNCV_CON_BUD_CLA.m
  braph2genesis/pipelines/connectivity NN/example_NNCV_CON_CLA.m
  braph2genesis/pipelines/connectivity NN/example_NNCV_CON_REG.m
  braph2genesis/pipelines/connectivity NN/example_NNCV_CON_WU_CLA.m
  braph2genesis/pipelines/connectivity NN/example_NNCV_CON_WU_M_REG.m
  braph2genesis/pipelines/connectivity NN/example_NN_CON_CLA.m
  braph2genesis/pipelines/connectivity NN/example_NN_CON_REG.m
  braph2genesis/src/nn/_NNCrossValidation.gen.m
Labels: enhancement

#141 Bug fix and check for all analyze ensemble BUD BUT
  braph2genesis/pipelines/connectivity/_AnalyzeEnsemble_CON_BUD.gen.m
  braph2genesis/pipelines/connectivity/_AnalyzeEnsemble_CON_BUT.gen.m
Labels: bug

#160 DEV for NN
  tutorials/developers/dev_nn_cla/dev_nn_cla.pdf
  tutorials/developers/dev_nn_cla/dev_nn_cla.tex
  tutorials/developers/dev_nn_cross_val/dev_nn_cross_val.pdf
  tutorials/developers/dev_nn_cross_val/dev_nn_cross_val.tex
  tutorials/developers/dev_nn_datapoint/dev_nn_datapoint.pdf
  tutorials/developers/dev_nn_datapoint/dev_nn_datapoint.tex
  tutorials/developers/dev_nn_reg/dev_nn_reg.pdf
  tutorials/developers/dev_nn_reg/dev_nn_reg.tex
  tutorials/developers/readme.md
Labels: documentation

#184 YC Update matlab version requirement
  README.md
  braph2/src/util/BRAPH2.m
  braph2genesis/src/util/BRAPH2.m
Labels: bug, documentation

#196 Comparison Ensemble Brain
  braph2genesis/src/analysis/_CompareEnsemblePP_CpDict.gen.m
  braph2genesis/src/analysis/_ComparisonEnsemble.gen.m
  braph2genesis/src/analysis/_ComparisonEnsembleBrainPF.gen.m
  braph2genesis/src/analysis/_ComparisonEnsembleBrainPF_BB.gen.m
  braph2genesis/src/analysis/_ComparisonEnsembleBrainPF_BS.gen.m
  braph2genesis/src/analysis/_ComparisonEnsembleBrainPF_BU.gen.m
  braph2genesis/src/analysis/_ComparisonEnsembleBrainPF_GB.gen.m
  braph2genesis/src/analysis/_ComparisonEnsembleBrainPF_GS.gen.m
  braph2genesis/src/analysis/_ComparisonEnsembleBrainPF_GU.gen.m
  braph2genesis/src/analysis/_ComparisonEnsembleBrainPF_NB.gen.m
  braph2genesis/src/analysis/_ComparisonEnsembleBrainPF_NS.gen.m
  braph2genesis/src/analysis/_ComparisonEnsembleBrainPF_NU.gen.m
Labels: enhancement

#197 Bz measure brain pf bz
  braph2genesis/src/analysis/_CompareGroupPP_CpDict.gen.m
  braph2genesis/src/analysis/_ComparisonGroup.gen.m
  braph2genesis/src/analysis/_ComparisonGroupBrainPF.gen.m
  braph2genesis/src/analysis/_ComparisonGroupBrainPF_BB.gen.m
  braph2genesis/src/analysis/_ComparisonGroupBrainPF_BS.gen.m
  braph2genesis/src/analysis/_ComparisonGroupBrainPF_BU.gen.m
  braph2genesis/src/analysis/_ComparisonGroupBrainPF_GB.gen.m
  braph2genesis/src/analysis/_ComparisonGroupBrainPF_GS.gen.m
  braph2genesis/src/analysis/_ComparisonGroupBrainPF_GU.gen.m
  braph2genesis/src/analysis/_ComparisonGroupBrainPF_NB.gen.m
  braph2genesis/src/analysis/_ComparisonGroupBrainPF_NS.gen.m
  braph2genesis/src/analysis/_ComparisonGroupBrainPF_NU.gen.m
Labels: enhancement

#204 Graph template and alayerlabel MP fix
  braph2genesis/pipelines/connectivity multiplex/_AnalyzeEnsemble_CON_MP_BUD.gen.m
  braph2genesis/pipelines/connectivity multiplex/_AnalyzeEnsemble_CON_MP_BUT.gen.m
  braph2genesis/pipelines/connectivity-functional multiplex/_AnalyzeEnsemble_CON_FUN_MP_BUD.gen.m
  braph2genesis/pipelines/connectivity-functional multiplex/_AnalyzeEnsemble_CON_FUN_MP_BUT.gen.m
  braph2genesis/pipelines/connectivity/_AnalyzeEnsemble_CON_BUD.gen.m
  braph2genesis/pipelines/connectivity/_AnalyzeEnsemble_CON_BUT.gen.m
  braph2genesis/pipelines/functional multiplex/_AnalyzeEnsemble_FUN_MP_BUD.gen.m
  braph2genesis/pipelines/functional multiplex/_AnalyzeEnsemble_FUN_MP_BUT.gen.m
  braph2genesis/pipelines/functional/_AnalyzeEnsemble_FUN_BUD.gen.m
  braph2genesis/pipelines/functional/_AnalyzeEnsemble_FUN_BUT.gen.m
  braph2genesis/src/analysis/_AnalyzeEnsemble.gen.m
  braph2genesis/src/analysis/_AnalyzeEnsemblePP_MeDict.gen.m
  braph2genesis/src/analysis/_ComparisonEnsemble.gen.m
  braph2genesis/src/analysis/_MeasureEnsemble.gen.m
Labels: bug

#213 HIDE/SHOW check
  braph2genesis/src/analysis/_AnalyzeEnsemblePP_GDict.gen.m
  braph2genesis/src/analysis/_AnalyzeEnsemblePP_MeDict.gen.m
  braph2genesis/src/analysis/_AnalyzeGroupPP_G.gen.m
  braph2genesis/src/analysis/_CompareEnsemblePP_CpDict.gen.m
  braph2genesis/src/analysis/_CompareGroupPP_CpDict.gen.m
Labels: bug
